import pygame
pygame.font.init()

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
FPS = 60
WINDOW_NAME = "Madness Combat: Zombies!"

GRAY_COLOR_TEMP = (128, 128, 128)
WHITE = (255, 255, 255)
LIGHT_GRAY = (211, 211, 211)
BG_MENU_COLOR = (50, 50, 50)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
DARK_GRAY = (50, 50, 50)
BLACK = (0, 0, 0)

BUTTON_FONT = pygame.font.SysFont(None, 36)
BASE_BUTTON_WIDTH = 200
BASE_BUTTON_HEIGHT = 50

ONE_EIGHT_OF_SCREEN_WIDTH = SCREEN_WIDTH // 8
ONE_EIGHT_OF_SCREEN_HEIGHT = SCREEN_HEIGHT // 8
ONE_FORTH_OF_SCREEN_HEIGHT = SCREEN_HEIGHT // 4
SCREEN_HEIGHT_MID = SCREEN_HEIGHT // 2
SCREEN_WIDTH_MID = SCREEN_WIDTH // 2

HITBOX_WIDTH = 100
HITBOX_HEIGHT = 250

WALL_CORDS_TUPLE = (((0,0),(ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT),(ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT * 3),(0, SCREEN_HEIGHT)),
                    ((SCREEN_WIDTH - ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT),(SCREEN_WIDTH, 0),(SCREEN_WIDTH, SCREEN_HEIGHT),(SCREEN_WIDTH - ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT * 3)),
                    ((ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT),(SCREEN_WIDTH - ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT),(SCREEN_WIDTH - ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT * 3),(ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT * 3)),
                    ((0, 0),(SCREEN_WIDTH, 0),(SCREEN_WIDTH - ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT),(ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT)),
)