import pygame
pygame.font.init()

#---SCREEN/WORLD SETTINGS---

SCREEN_WIDTH = 3440
SCREEN_HEIGHT = 1080
CAMERA_SCREEN_WIDTH = 1920
SHOP_ROOM_WIDTH = 1920
SHOP_ROOM_HEIGHT = 1080
MAX_CAMERA_X_ARENA = SCREEN_WIDTH - CAMERA_SCREEN_WIDTH
MAX_CAMERA_X_SHOP = SHOP_ROOM_WIDTH - CAMERA_SCREEN_WIDTH
FPS = 60
WINDOW_NAME = "Madness Combat: Zombies!"

#---COLORS---

GRAY_COLOR_TEMP = (128, 128, 128)
WHITE = (255, 255, 255)
LIGHT_GRAY = (211, 211, 211)
BG_MENU_COLOR = (50, 50, 50)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
DARK_GRAY = (50, 50, 50)
SLIGHTLY_BRIGHTER_DARK_GRAY = (80, 80, 80)
BLACK = (0, 0, 0)
ZOMBIE_GREEN = (84, 197, 113)
BULLET_YELLOW = (175, 155, 96)
WOOD_COLOR = (186, 140, 99)

#---FONT LEFTOVERS---

BUTTON_FONT = pygame.font.SysFont(None, 36)
BASE_BUTTON_WIDTH = 200
BASE_BUTTON_HEIGHT = 50

#---PARTS OF THE MAIN PLAY AREA---

ONE_EIGHT_OF_SCREEN_WIDTH = SCREEN_WIDTH // 8
ONE_EIGHT_OF_SCREEN_HEIGHT = SCREEN_HEIGHT // 8
ONE_FORTH_OF_SCREEN_HEIGHT = SCREEN_HEIGHT // 4
SCREEN_HEIGHT_MID = SCREEN_HEIGHT // 2
SCREEN_WIDTH_MID = SCREEN_WIDTH // 2

#---PARTS OF THE SHOP AREA---

ONE_EIGHT_OF_SHOP_ROOM_WIDTH = SHOP_ROOM_WIDTH // 8
ONE_EIGHT_OF_SHOP_ROOM_HEIGHT = SHOP_ROOM_HEIGHT // 8
ONE_FORTH_OF_SHOP_ROOM_HEIGHT = SHOP_ROOM_HEIGHT // 4
SHOP_ROOM_HEIGHT_MID = SHOP_ROOM_HEIGHT // 2
SHOP_ROOM_WIDTH_MID = SHOP_ROOM_WIDTH // 2

#---BASE HITBOX VALUES---

HITBOX_WIDTH = 50
HITBOX_HEIGHT = 100

#---ZOMBIE SETTINGS---

ZOMBIE_SPEED = 100
ZOMBIE_DAMAGE = 10
ZOMBIE_HEALTH = 50
ZOMBIE_SPAWN_TIMER = 0
ZOMBIE_SPAWN_DELAY = 5
ZOMBIE_RAPID_SPAWN_TIMER = 0
ZOMBIE_RAPID_SPAWN_DELAY = 0.5

#---POLYGON BUILDING POINTS---

WALL_CORDS_TUPLE = (
    (
        (0,0),
        (ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT),
        (ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT * 3),
        (0, SCREEN_HEIGHT)
    ),
    (
        (SCREEN_WIDTH - ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT),
        (SCREEN_WIDTH, 0),
        (SCREEN_WIDTH, SCREEN_HEIGHT),
        (SCREEN_WIDTH - ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT * 3)
    ),
    (
        (ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT),
        (SCREEN_WIDTH - ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT),
        (SCREEN_WIDTH - ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT * 3),
        (ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT * 3)
    ),
    (
        (0, 0),
        (SCREEN_WIDTH, 0),
        (SCREEN_WIDTH - ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT),
        (ONE_EIGHT_OF_SCREEN_WIDTH, ONE_FORTH_OF_SCREEN_HEIGHT)
    ),
)

WALL_CORDS_TUPLE_SHOP = (
    (
        (0,0),
        (ONE_EIGHT_OF_SHOP_ROOM_WIDTH, ONE_FORTH_OF_SHOP_ROOM_HEIGHT),
        (ONE_EIGHT_OF_SHOP_ROOM_WIDTH, ONE_FORTH_OF_SHOP_ROOM_HEIGHT * 3),
        (0, SHOP_ROOM_HEIGHT),
    ),
    (
        (SHOP_ROOM_WIDTH - ONE_EIGHT_OF_SHOP_ROOM_WIDTH, ONE_EIGHT_OF_SHOP_ROOM_HEIGHT),
        (SHOP_ROOM_WIDTH, 0),
        (SHOP_ROOM_WIDTH, SHOP_ROOM_HEIGHT),
        (SHOP_ROOM_WIDTH - ONE_EIGHT_OF_SHOP_ROOM_WIDTH, ONE_FORTH_OF_SHOP_ROOM_HEIGHT * 3)
    ),
    (
        (ONE_EIGHT_OF_SHOP_ROOM_WIDTH, ONE_FORTH_OF_SHOP_ROOM_HEIGHT),
        (SHOP_ROOM_WIDTH - ONE_EIGHT_OF_SHOP_ROOM_WIDTH, ONE_FORTH_OF_SHOP_ROOM_HEIGHT),
        (SHOP_ROOM_WIDTH - ONE_EIGHT_OF_SHOP_ROOM_WIDTH, ONE_FORTH_OF_SHOP_ROOM_HEIGHT * 3),
        (ONE_EIGHT_OF_SHOP_ROOM_WIDTH, ONE_FORTH_OF_SHOP_ROOM_HEIGHT * 3)
    ),
    (
        (0, 0),
        (SHOP_ROOM_WIDTH, 0),
        (SHOP_ROOM_WIDTH - ONE_EIGHT_OF_SHOP_ROOM_WIDTH, ONE_FORTH_OF_SHOP_ROOM_HEIGHT),
        (ONE_EIGHT_OF_SHOP_ROOM_WIDTH, ONE_FORTH_OF_SHOP_ROOM_HEIGHT),
    )
)

ENTRY_POINTS_TUPLE = ((
        (SCREEN_WIDTH_MID - 50, ONE_EIGHT_OF_SCREEN_HEIGHT * 5),
        (SCREEN_WIDTH_MID + 50, ONE_EIGHT_OF_SCREEN_HEIGHT * 5),
        (SCREEN_WIDTH_MID + 50, ONE_FORTH_OF_SCREEN_HEIGHT * 3),
        (SCREEN_WIDTH_MID - 50, ONE_FORTH_OF_SCREEN_HEIGHT * 3)
    ),
)